// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bliwnrikjfzcialoznur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsaXducmlramZ6Y2lhbG96bnVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MDkwNDYsImV4cCI6MjA2NTA4NTA0Nn0.KVx5uaBmj5_IESBMgB7H72tWCBKWuj2-IU-9HpunCC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);